service: sample-app
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: dev
  memorySize: 128
  role: ${file(./serverlessconfig.js):config.role}
  
  
    
functions:
  app:
    handler: index.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true